[workspace]
release = false
release_always = false
git_only = false
publish = false
publish_no_verify = true
semver_check = true
changelog_update = false
changelog_config = "cliff.toml"
git_release_enable = false

[[package]]
name = "timeseries-table-format"
release = true
changelog_update = true
changelog_path = "crates/timeseries-table-format/CHANGELOG.md"
git_release_enable = true

[[package]]
name = "timeseries-table-core"
release = true
changelog_update = true
changelog_path = "crates/timeseries-table-core/CHANGELOG.md"
git_release_enable = true

[[package]]
name = "timeseries-table-datafusion"
release = true
changelog_update = true
changelog_path = "crates/timeseries-table-datafusion/CHANGELOG.md"
git_release_enable = true

[[package]]
name = "timeseries-table-cli"
release = true
changelog_update = true
changelog_path = "crates/timeseries-table-cli/CHANGELOG.md"
git_release_enable = true

[[package]]
name = "timeseries-table-python"
release = true
git_only = true
git_tag_name = "timeseries-table-python-v{{ version }}"
semver_check = false
changelog_update = true
changelog_path = "crates/timeseries-table-python/CHANGELOG.md"
git_release_enable = true
