[workspace]
release = false
release_always = false
git_only = true
publish = false
changelog_update = false
changelog_config = "cliff.toml"
git_release_enable = false

[[package]]
name = "timeseries-table-format"
release = true
changelog_update = true
changelog_path = "crates/timeseries-table-format/CHANGELOG.md"
git_release_enable = true

[[package]]
name = "timeseries-table-core"
release = true
changelog_update = true
changelog_path = "crates/timeseries-table-core/CHANGELOG.md"

[[package]]
name = "timeseries-table-cli"
release = false

[[package]]
name = "timeseries-table-datafusion"
release = false
