[project]
name = "timeseries-table-format"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyarrow>=23.0.0",
]

[build-system]
requires = ["maturin>=1.11. <2.0"]
build-backend = "maturin"

[tool.maturin]
manifest-path = "../crates/timeseries-table-python/Cargo.toml"
bindings = "pyo3"