[package]
name = "timeseries-table-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
datafusion = { workspace = true }
snafu = { workspace = true }
tokio = { workspace = true, features = ["fs", "rt-multi-thread", "macros"] }

timeseries-table-core = { path = "../timeseries-table-core" }
timeseries-table-datafusion = { path = "../timeseries-table-datafusion" }

[dev-dependencies]
arrow = { workspace = true }
parquet = { workspace = true }
tempfile = "3"

[lints]
workspace = true
